version: "3"
services:
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 8080:80
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8090:90
